#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
geeknode = "E2AD6314D9A36BF9557B62759C4188B82AEB6C06BB0B4C0B8D03B49E109B14A381C081B8F69551DFA8255A84E34E8B631384C23D03"
sharewood_pass = "31BE5E68DC5447A486CFB7C91537E4FF3434E08D79AEF1FDFD4E6B8E5F0E0009755010A9ECFCEDBEE537D664E2D3BEB072C353D25601BE78"
