#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
geeknode = "F6842EDC023883662A22B823D7CF8F5D5C00F0A0349DDB38491BE5B8D4A44F8F45CE7F1CBF3542F5822AAED99B227C4EF3AA4848C2"
sharewood_pass = "2320E189852FFEE26CCDD1C645BFC474263A619549084708C3FC5100838278DF3C320AFBD05A3EE7DB3465F4C5BD83709476FA5EBBE50444"
