[Proton]
source = notmuch://~/.mail
outgoing = smtp://samtroulfion%40proton.me:ps_fMoNmYNfeqZq6O59Rvw@127.0.0.1:1025
maildir-store = ~/.mail
maildir-account-path = proton
check-mail = 1m
check-mail-cmd = mbsync -c ~/.config/isyncrc proton && notmuch new
check-mail-timeout = 2m

query-map = ~/.config/aerc/proton-notmuch-queries
exclude-tags = deleted,spam

from = Adrien Duarte <samtroulfion@proton.me>
default = INBOX

[GmailServarr]
source = notmuch://~/.mail
maildir-store = ~/.mail
maildir-account-path = gmailservarr
check-mail = 1m
check-mail-cmd = mbsync -c ~/.config/isyncrc gmailservarr && notmuch new
check-mail-timeout = 2m

query-map = ~/.config/aerc/gmailservarr-notmuch-queries
exclude-tags = deleted,spam

from = Dirty <servarr.dirty@gmail.com>
default = INBOX

