[theme]
background = "#1a1a1a"
primary = "#d7c6ac"        # crème
secondary = "#b03060"      # bordeaux
title = "#ff5e5e"          # rouge clair
highlight = "#666666"      # gris foncé
playing = "#ff5e5e"
paused = "#d7c6ac"
bar = "#b03060"
bar_background = "#2e2e2e"

